version: "3"
services:
  smart-production:
    build: .
    # ports:
    #   - "5000:5000" ## Run ปกติ
    environment:
      - NODE_ENV=production
      - DB_USER=prodtusr
      - DB_PASSWORD=Pro1767*
      - SESSION_SECRET=your-secure-session-secret
      - HOST=0.0.0.0
      - COOKIE_DOMAIN=localhost
      - COOKIE_SECURE=false
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./sessions:/usr/src/app/sessions

  web:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "5050:5050" # กัน Port ชน
    depends_on:
      - smart-production
    networks:
      - app-network
    volumes:
      - ./logs/nginx:/var/log/nginx
    restart: unless-stopped

networks:
  app-network:
    driver: bridge



# # Old- OK
# version: "3"
# services:
#   smart-production:
#     build: .
#     ports:
#       - "5000:5000"
#     environment:
#       - NODE_ENV=production
#       - DB_USER=prodtusr
#       - DB_PASSWORD=Pro1767*
#       - SESSION_SECRET=your-secure-session-secret
#       - HOST=0.0.0.0
#       - COOKIE_DOMAIN=localhost
#       - COOKIE_SECURE=false
#     extra_hosts:
#       - "host.docker.internal:host-gateway"